packages:
  # all packages in subdirs of packages/ and components/
  - 'packages/**'
  - 'examples/*'
  - 'docs-new'
  - 'docs'
  # exclude packages that are inside test directories
  - '!**/test/**'