is-t-func:
  any:
    - kind: call_expression
  has:
    kind: identifier
    regex: ^t$
is-message-arg:
  kind: arguments
  inside:  
    matches: is-t-func
is-t-component:
  any:
    - kind: jsx_self_closing_element
    - kind: jsx_opening_element
    - kind: jsx_element
  has:
    kind: identifier
    regex: ^Translate$
is-message-attr:
  kind: jsx_attribute
  has:
    kind: property_identifier
    regex: ^message$
  inside:  
    matches: is-t-component
is-vars-attr:
  kind: jsx_attribute
  has:
    kind: property_identifier
    regex: ^vars$
  inside:        
    matches: is-t-component     
is-options-attr:
  kind: jsx_attribute
  has:
    kind: property_identifier
    regex: ^options$
  inside:        
    matches: is-t-component     